### PR TITLE
Sync staging and prod

### PR DESCRIPTION
**Pull request by ismail-shahzad**
This PR syncs prod with staging so that its up to date with the latest features deployed on staging.

@luccasmmg @steveoni we need these three secrets added for the prod env

- `secrets.PROD_FRONTEND_NEXTAUTH_URL`
- `secrets.PROD_NEXT_PUBLIC_GTM_ID`
- `secrets.PROD_NEXT_PUBLIC_HOTJAR_ID`

### CODE REVIEW

**Comment by luccasmmg** [comment]
secrets.PROD_FRONTEND_NEXTAUTH_URL

This one is the same url as the actual frontend ex in dev its https://wri.dev.frontend.datopian.com 

The other ones only stephen knows

**Comment by steveoni** [comment]
> This PR syncs prod with staging so that its up to date with the latest features deployed on staging.
> 
> @luccasmmg @steveoni we need these three secrets added for the prod env
> 
> * `secrets.PROD_FRONTEND_NEXTAUTH_URL`
> * `secrets.PROD_NEXT_PUBLIC_GTM_ID`
> * `secrets.PROD_NEXT_PUBLIC_HOTJAR_ID`

@MuhammadIsmailShahzad we don't have any for prod. you can use the staging one for now.  we will need to ask them to provide one

**Review by mpolidori — APPROVED** [review]
Looks good. There are 2 secrets needed in `wri-odp-secrets` though.

For Prod backend CKAN:
```
CKANEXT__WRI__MIGRATION_DEPLOYMENT_ENV: prod
```

For Prod Migration App:
```
FLOW_DEPLOYMENT_ENV: prod
```

**Comment by ismail-shahzad** [comment]
@mpolidori Added here https://github.com/wri/wri-odp-secrets/blob/main/k8s-secrets/prod/wri-prod-migration-app-envvars.yaml and https://github.com/wri/wri-odp/pull/436/commits/5524c0b5d79eb8df7a368c207186bd59f5cbba6e

**Comment by ismail-shahzad** [comment]
@steveoni ok using STAGING values for now. We can update once we have PROD values.

**Review by luccasmmg — APPROVED** [review]
lgtm

**Pull request merged**
