### PR TITLE
Add CKAN backend development environment

### PR DESCRIPTION
**Pull request by mpolidori**
This PR adds the Docker Compose CKAN development environment, along with the initial Cypress integration test scaffolding.

### CODE REVIEW

**Comment by mpolidori** [comment]
@tanderegg @dmannarino This is the backend CKAN dev environment with initial tests included (just wanted to keep you in the loop).

Let me know if you'd prefer I just tag you instead of assigning you as reviewers moving forward and feel free to ping me (here or on Slack) if you have any questions.

**Review by demenech — APPROVED** [review]
Setup was easy, got the env running and tested a few operations including pushing a resource to datapusher. Tests are working fine as well. LGTM.

**Review by dmannarino — APPROVED** [review]
Looks good! Sorry it took so long for me to check it out, will be much speedier in the future!

**Comment by mpolidori** [comment]
@dmannarino No problem, thanks!

**Pull request merged**
