### PR TITLE
Search page

### PR DESCRIPTION
**Pull request by luccasmmg**
Implements the advanced search page

image
image

image
image

### CODE REVIEW

**Comment by steveoni** [comment]
Review

1. Font family Acumin is not picked up by the browser- it currently uses Sans-serif
2. The mockup uses a viewport of 1440px so for a larger screen the content is meant to be centered. this was pointed out to me also by @demenech ( might not apply since this has a sidebar, maybe we should all discuss this including Monika)
3. Show and Sort by dropdown looks broken after selecting
Screenshot 2023-10-19 at 10 11 23

4. The title looks more spacious on mobile when wrapped
Screenshot 2023-10-19 at 10 16 51

5. I don't think this should be an issue, but on some mobile, this looks not aligned:
Screenshot 2023-10-19 at 10 17 38

Apart from this everything looks good

**Comment by luccasmmg** [comment]
The font family at least on my computer and cell phone has been picked up correctly
image
Points 3 and 4 have been fixed
Point 5 has been fixed up to 360px

@steveoni you need to add a review instead of just a commit, otherwise we cant merge it

**Comment by steveoni** [comment]
@luccasmmg what about point 2 what do you think?

**Comment by luccasmmg** [comment]
> @luccasmmg what about point 2 what do you think?

This seems fine, dont you think? 4k resolution 

image

**Review by steveoni — APPROVED** [review]
lgtm!

**Pull request merged**
