### PR TITLE
Odp 166: Delete all entities from Dashboard

### PR DESCRIPTION
**Pull request by steveoni**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [ ] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: ODP-166

## What is the new behavior?

Delete all entities in Dashboard
-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by luccasmmg — CHANGES_REQUESTED** [review]
We alreaddy  have a Tooltip component being used https://github.com/wri/wri-odp/blob/dev/deployment/frontend/src/components/_shared/Tooltip.tsx its there since 3 weeks ago, if you add a new one its going to end up being blocked in QA because a lack of consistency

**Review by luccasmmg — CHANGES_REQUESTED** [review]
One other thging i noticed is that the edit button is not wired up, it should be a link to /dashboard/{teams/topics}/{teamName/topicName}/edit

**Review by luccasmmg — CHANGES_REQUESTED** [review]
One other thing is that altough you added a confirmation modal for the deletion(Something which i completely forgot in the delete button for the edit pages, you can make a little bit prettier just copy it from tailwind ui

https://tailwindui.com/components/application-ui/overlays/modals

**Comment by steveoni** [comment]
> We alreaddy have a Tooltip component being used https://github.com/wri/wri-odp/blob/dev/deployment/frontend/src/components/_shared/Tooltip.tsx its there since 3 weeks ago, if you add a new one its going to end up being blocked in QA because a lack of consistency

that tooltip is too verbose compared to this, can't we change it to this. or maybe there is another way of setting the one we have now, instead of setting up provider, triggers and the likes we can make it less of such

**Comment by steveoni** [comment]
> One other thing is that altough you added a confirmation modal for the deletion(Something which i completely forgot in the delete button for the edit pages, you can make a little bit prettier just copy it from tailwind ui
> 
> https://tailwindui.com/components/application-ui/overlays/modals

For this we don't have much info to display alongside the delete. so my current implementation is based on how github handle deletion of repo. you can also check that out

**Comment by luccasmmg** [comment]
> > One other thing is that altough you added a confirmation modal for the deletion(Something which i completely forgot in the delete button for the edit pages, you can make a little bit prettier just copy it from tailwind ui
> > https://tailwindui.com/components/application-ui/overlays/modals
> 
> For this we don't have much info to display alongside the delete. so my current implementation is based on how github handle deletion of repo. you can also check that out

ok, fine by me

**Review by luccasmmg — APPROVED** [review]
LGTM

**Pull request merged**
