### PR TITLE
Odp 154

### PR DESCRIPTION
**Pull request by steveoni**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [x] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the current behavior?

Issue Number: ODP-154

## What is the new behavior?

-
-
-

## Does this introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

Screenshot 2023-10-31 at 11 40 29
Screenshot 2023-10-31 at 11 40 40
Screenshot 2023-10-31 at 11 42 02

### CODE REVIEW

**Review by luccasmmg — COMMENTED** [review]
I cant see this section in your code
image

**Comment by luccasmmg** [comment]
This arrow should be lower when you have tha approval header

image

**Comment by steveoni** [comment]
> I cant see this section in your code image

actually thought this was part of dataset page implementation. will update it

**Comment by steveoni** [comment]
@luccasmmg this now updated

**Review by luccasmmg — APPROVED** [review]
LGTM

**Pull request merged**
